### ISSUE TITLE
How to diagnose auth issue in 'faz project provision'

### ISSUE THREAD

**Issue by davidebbo** [arafato/funcy-azure#1]
When I run:

```
faz project provision -g FAZTEST -l westus -s FAZ-WebPlan
```

It fails with:

```
Starting provisioning / updating your project... (this may take up to ~3 mins)

DONE!
Creating/Updating Resource Group... \FAILED!
Ups. Something went wrong. See error message for details.
FuncyAzureError: Unable to provision project: Failed to acquire token for application with the provided secret.
Error: Get Token request returned http error: 401 and server response: {"error":"invalid_client","error_description":"AADSTS70002: Error validating credentials. AADSTS50012: Invalid client secret is provided.\r\nTrace ID: ca4bd77d-c574-4db6-a369-5a4fd8fd8f81\r\nCorrelation ID: 269eaa47-38df-4d1c-ac07-1108c195e412\r\nTimestamp: 2016-05-23 01:07:48Z","error_codes":[70002,50012],"timestamp":"2016-05-23 01:07:48Z","trace_id":"ca4bd77d-c574-4db6-a369-5a4fd8fd8f81","correlation_id":"269eaa47-38df-4d1c-ac07-1108c195e412"}
    at new FuncyAzureError (C:\Users\David\AppData\Roaming\npm\node_modules\funcy-azure\lib\Error.js:8:9)
    at C:\Users\David\AppData\Roaming\npm\node_modules\funcy-azure\lib\handlers\ProjectProvisionHandler.js:102:13
    etc...
```

But I'm pretty sure I have the right info in `admin.env`.

If I instead use those same values with `azure login`, it works fine:

```
azure login --service-principal --tenant {tenant} -u {appid} -p {password}
```

Any idea what might be the issue and how to diagnose it?

**Comment by davidebbo** [comment]
I was trying to use a Service Principal obtained using [this workflow](http://blog.davidebbo.com/2014/12/azure-service-principal.html), and for some reason that doesn't work. But when going through the steps in [this doc](https://azure.microsoft.com/en-us/documentation/articles/resource-group-authenticate-service-principal/#authenticate-with-password---azure-cli) (as suggested in your quick start) it does in fact work.

I don't understand it, but oh well. AAD is hard :)
